"""
Contains data and functionality common to the codegen and chaigen scripts.
"""

import os

# "//GENERATED" should be at the very top of every autogenerated file. It is inserted using .format() into the prelude.
codegen_initial_comment = "//GENERATED"

# The prelude should be at the start of every autogenerated file.
prelude = """{}
// This file was auto-generated by the codegen utility. Do not edit (edits will be overwritten on when codegen is
// next ran).

#pragma once
"""

# Add types to this list to cause them to be generate argument types for copying, rather than as a const reference.
copyable_types = {
    "int", "bool"  # TODO: this can be expanded
}


def file_is_generated(path):
    """
    Test if a given file has been generated by checking if it starts with the prefix comment `codegen_initial_comment`
    ("//GENERATED").
    :param path: The path to the file to test.
    :return: Whether the file has been generated
    """
    if os.path.exists(path):
        with open(path, 'r') as f:
            first_line = f.readline()
            if not first_line.startswith(codegen_initial_comment):
                return False
    return True
